### ISSUE TITLE
use of `files()` from `importlib.resources` appears incorrect

### ISSUE THREAD

**Issue by rwightman** [facebookresearch/imagenetx#2]
The builtin for Python 3 should be used like 

`files("imagenet_x") / "annotations"`

`files(imagenet_x.annotations)` throws an exception

**Comment by BadrYoubiIdrissi** [comment]
Thank you for signalling this bug ! Somehow it worked on my side, had you installed the module? 

I've fixed it and pushed to main [eddff58](https://github.com/facebookresearch/imagenetx/commit/eddff5859c44def10408dc0e6149ee7272f8f4b2).

Thank you for your interest in Imagenet-X !
